@startuml

title シナリオステート図

[*] -down-> 現在の状態を確認
現在の状態を確認 -right-> フェーズ開始
フェーズ開始 -right-> シナリオムービー
フェーズ開始 -right-> カスタマイズ画面
フェーズ開始 -right-> バトル画面
シナリオムービー -right-> カスタマイズ画面
シナリオムービー -up-> バトル画面
シナリオムービー -down-> フェーズ終了
カスタマイズ画面 -down-> シナリオムービー
カスタマイズ画面 -up-> バトル画面
バトル画面 -> シナリオムービー
バトル画面 -down-> フェーズ終了
フェーズ終了 -up-> フェーズ開始

フェーズ開始 : シナリオへ移動
フェーズ開始 : カスタマイズへ移動
フェーズ開始 : バトルへ移動

シナリオムービー : カスタマイズへ移動
シナリオムービー : バトルへ移動
シナリオムービー : フェーズ終了

カスタマイズ画面 : シナリオへ移動
カスタマイズ画面 : バトルへ移動

バトル画面 : シナリオへ移動
バトル画面 : フェーズ終了

フェーズ終了 : フェーズが終了したことを保存
フェーズ終了 : 次フェーズを開始

@enduml