@startuml

title マルチプレイステート図

[*] -down-> 部屋選択画面

部屋選択画面 -right-> 部屋作成画面
部屋選択画面 -> ロビー
部屋選択画面 -down-> カスタマイズ画面
部屋選択画面 : 作成済み部屋を一覧検索できる
部屋選択画面 : 部屋作成画面で自分で部屋を作る
部屋選択画面 : 部屋を選んでロビーへ
部屋選択画面 : カスタマイズを事前にしておく

部屋作成画面 -> ロビー
部屋作成画面 -left-> 部屋選択画面
部屋作成画面 : ルールを選択できる
部屋作成画面 : 部屋に鍵をかけられる
部屋作成画面 : やっぱやめるで部屋選択画面に戻れる

ロビー -right-> バトル画面
ロビー -> カスタマイズ画面
ロビー -> 部屋作成画面
ロビー : 部屋作成者がバトル開始
ロビー : カスタマイズ画面でチームに合わせてカスタマイズできる
ロビー : 部屋の作り直しができる
ロビー : 対戦相手を待つ
ロビー : 時間経過で設定画面に戻る

カスタマイズ画面 -up-> 部屋選択画面
カスタマイズ画面 -> ロビー
カスタマイズ画面 : 設定画面から遷移した場合自由に設定画面に戻れる
カスタマイズ画面 : リザルト画面から遷移した場合時間経過でロビーに戻る

バトル画面 -right-> リザルト画面
バトル画面 : バトル始める
バトル画面 : 勝敗がついたらリザルト画面へ移動

リザルト画面 -up-> 部屋選択画面
リザルト画面 -down-> ロビー
リザルト画面 -left-> カスタマイズ画面
リザルト画面 : 再度挑戦のためにロビーへ移動
リザルト画面 : カスタマイズして再戦するためにカスタマイズ画面へ移動
リザルト画面 : ゲームを終わるために設定画面に移動

@enduml